trigger:
  branches:
    include:
      - main

stages:
  - stage: Build
    displayName: 'Build and Test'
    jobs:
      - job: BuildAndTest
        displayName: 'Build and Test'
        pool:
          vmImage: 'ubuntu-latest'  # Select the desired VM image

        steps:
          - script: |
              mvn clean install
            displayName: 'Build with Maven'

  - stage: Deploy
    displayName: 'Deploy to Docker'
    dependsOn: Build
    jobs:
      - job: DeployToDocker
        displayName: 'Deploy to Docker'
        pool:
          vmImage: 'ubuntu-latest'  # Select the desired VM image

        steps:
          - task: Docker@2
            inputs:
              repository: 'my-app-repo'  # Replace with the name of your Docker repository
              command: 'buildAndPush'
              Dockerfile: 'Dockerfile'
              tags: 'latest'  # Adjust the Docker image tag as per your requirements
