trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'Build an image'
  inputs:
    containerRegistry: 'ExplorationTask' # Replace with your container registry connection name
    repository: 'my-app-repo' # Replace with the name of your repository
    Dockerfile: 'Dockerfile'
    buildContext: '.'

- task: Docker@2
  displayName: 'Push an image'
  inputs:
    containerRegistry: 'ExplorationTask' # Replace with your container registry connection name
    repository: 'my-app-repo' # Replace with the name of your repository
    command: 'push'

- script: 'mvn clean install'
  displayName: 'Build with Maven'

- script: 'mvn test'
  displayName: 'Run Tests'
